// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rota.Modules.Recommendation.Infrastructure.Persistence;

#nullable disable

namespace Rota.Modules.Recommendation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecommendationDbContext))]
    partial class RecommendationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recommendation")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendationRun", b =>
                {
                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("AvailableMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("available_minutes");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("failure_code");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model_version");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("NeighborhoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighborhood_id");

                    b.Property<string>("OverallExplanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("overall_explanation");

                    b.Property<string>("RegionExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("region_explanation");

                    b.Property<string>("RegionName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("region_name");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<double?>("RegionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("region_score");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<string>("TasteProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("taste_profile_json");

                    b.Property<DateOnly>("TripDate")
                        .HasColumnType("date")
                        .HasColumnName("trip_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_recommendation_runs_correlation_id");

                    b.HasIndex("Status", "NextAttemptAt", "RequestedAt")
                        .HasDatabaseName("ix_recommendation_runs_job_queue");

                    b.HasIndex("Status", "ProcessingStartedAt")
                        .HasDatabaseName("ix_recommendation_runs_processing_lease");

                    b.HasIndex("UserId", "RequestedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_recommendation_runs_user_requested_at");

                    b.ToTable("recommendation_runs", "recommendation");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Infrastructure.Outbox.RecommendationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_messages_aggregate_type");

                    b.HasIndex("Status", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_dispatch_queue");

                    b.HasIndex("Status", "ProcessingStartedAt")
                        .HasDatabaseName("ix_outbox_messages_processing_lease");

                    b.ToTable("outbox_messages", "recommendation");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendationTimelineItem", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("place_name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("RunId", "Sequence");

                    b.HasIndex("PlaceId");

                    b.ToTable("timeline_items", "recommendation");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendedPlace", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("RunId", "Order");

                    b.HasIndex("PlaceId");

                    b.ToTable("recommended_places", "recommendation");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendationTimelineItem", b =>
                {
                    b.HasOne("Rota.Modules.Recommendation.Domain.Entities.RecommendationRun", "Run")
                        .WithMany("Timeline")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendedPlace", b =>
                {
                    b.HasOne("Rota.Modules.Recommendation.Domain.Entities.RecommendationRun", "Run")
                        .WithMany("Places")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Rota.Modules.Recommendation.Domain.Entities.RecommendationRun", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
