// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rota.Modules.Discovery.Infrastructure.Persistence;

#nullable disable

namespace Rota.Modules.Discovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    [Migration("20260716070648_InitialPostGis")]
    partial class InitialPostGis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discovery")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaceTag", b =>
                {
                    b.Property<Guid>("place_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.HasKey("place_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("place_tags", "discovery");

                    b.HasData(
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000001"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000001"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000002"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000002"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000003"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000003"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000004"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000004"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000005"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000005"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000006"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000006"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000007"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000007"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000008"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000008"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000009"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000009"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000010"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000010"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000011"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000011"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000012"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000012"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000013"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000013"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000014"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000014"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000015"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000015"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000016"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000016"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000017"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000017"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000018"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000018"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000019"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000019"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000020"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000020"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000021"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000021"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000022"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000022"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000023"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000023"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000024"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000024"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000025"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000025"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000026"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000026"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000027"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000027"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000028"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000028"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000029"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000029"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000030"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000030"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000031"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000031"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000032"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000032"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000033"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000033"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000034"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000034"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000035"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000035"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000036"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            place_id = new Guid("50000000-0000-0000-0000-000000000036"),
                            tag_id = new Guid("40000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", "discovery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Kafe",
                            Slug = "kafe"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "Restoran",
                            Slug = "restoran"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Müze",
                            Slug = "muze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "Park",
                            Slug = "park"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "Sanat",
                            Slug = "sanat"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Name = "Alışveriş",
                            Slug = "alisveris"
                        });
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Name")
                        .IsUnique();

                    b.ToTable("cities", "discovery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CountryCode = "TR",
                            Name = "İstanbul"
                        });
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("boundary");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_neighborhoods_boundary_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.ToTable("neighborhoods", "discovery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Boundary = (NetTopologySuite.Geometries.MultiPolygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;MULTIPOLYGON (((29.02 40.978, 29.035 40.978, 29.035 40.992, 29.02 40.992, 29.02 40.978)))"),
                            CityId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Caferağa"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Boundary = (NetTopologySuite.Geometries.MultiPolygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;MULTIPOLYGON (((29 41.035, 29.018 41.035, 29.018 41.052, 29 41.052, 29 41.035)))"),
                            CityId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Boundary = (NetTopologySuite.Geometries.MultiPolygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;MULTIPOLYGON (((28.968 41.018, 28.99 41.018, 28.99 41.03, 28.968 41.03, 28.968 41.018)))"),
                            CityId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Karaköy"
                        });
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighborhood_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_places_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("NeighborhoodId", "CategoryId");

                    b.ToTable("places", "discovery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Address = "Moda Cd., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0257 40.9848)"),
                            Name = "Moda Kahve Noktası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Address = "Sakızgülü Sk., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0272 40.9871)"),
                            Name = "Caferağa Sofrası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Address = "Moda Sahili, Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0231 40.981)"),
                            Name = "Moda Sahil Parkı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Address = "Neşe Sk., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0298 40.988)"),
                            Name = "Kadıköy Sanat Atölyesi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Address = "Moda Cd., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0264 40.9857)"),
                            Name = "Moda Tasarım Pazarı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Address = "Bahariye Cd., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.031 40.9901)"),
                            Name = "Bahariye Kitap Kafe",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Address = "Rıhtım Yolu, Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0218 40.986)"),
                            Name = "Sahil Lokantası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            Address = "Dr. Esat Işık Cd., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0286 40.9832)"),
                            Name = "Mahalle Kültür Evi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            Address = "Halil Ethem Sk., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0302 40.985)"),
                            Name = "Moda Sahnesi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            Address = "Moda Burnu, Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0222 40.9799)"),
                            Name = "Günbatımı Kahvesi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            Address = "Şair Nefi Sk., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0321 40.9878)"),
                            Name = "Caferağa Plakçısı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000012"),
                            Address = "Leylek Sk., Kadıköy",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0248 40.989)"),
                            Name = "Moda Vegan Mutfağı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000013"),
                            Address = "Köyiçi Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0058 41.0433)"),
                            Name = "Çarşı Kahve Evi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000014"),
                            Address = "Şehit Asım Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0069 41.0445)"),
                            Name = "Beşiktaş Esnaf Lokantası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000015"),
                            Address = "Dolmabahçe Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0051 41.0417)"),
                            Name = "Deniz Müzesi Çevresi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000016"),
                            Address = "Abbasağa, Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0098 41.048)"),
                            Name = "Abbasağa Dinlenme Alanı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000017"),
                            Address = "Süleyman Seba Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0038 41.041)"),
                            Name = "Akaretler Galeri",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000018"),
                            Address = "Ortabahçe Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0078 41.0451)"),
                            Name = "Çarşı Tasarım Dükkanı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000019"),
                            Address = "Ihlamurdere Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0118 41.0466)"),
                            Name = "Ihlamur Bahçe Kafe",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000020"),
                            Address = "İskele Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0044 41.0428)"),
                            Name = "Boğaz Balık Mutfağı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000021"),
                            Address = "Barbaros Blv., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0088 41.042)"),
                            Name = "Beşiktaş Performans Alanı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000022"),
                            Address = "Palanga Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0147 41.0495)"),
                            Name = "Yıldız Yürüyüş Noktası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000023"),
                            Address = "Beşiktaş İskele, Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.003 41.0438)"),
                            Name = "Vapur İskelesi Kahvesi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000024"),
                            Address = "Nüzhetiye Cd., Beşiktaş",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.0128 41.0456)"),
                            Name = "Yerel Üretici Pazarı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000025"),
                            Address = "Kemankeş Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9784 41.0221)"),
                            Name = "Karaköy Kavurma Evi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000026"),
                            Address = "Rıhtım Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.976 41.0212)"),
                            Name = "Liman Mutfağı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000027"),
                            Address = "Tersane Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9735 41.024)"),
                            Name = "Tarihi Liman Sergisi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000028"),
                            Address = "Boğazkesen Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9822 41.0261)"),
                            Name = "Tophane Sanat Alanı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000029"),
                            Address = "Mumhane Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9798 41.0235)"),
                            Name = "Karaköy Tasarım Hanı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000030"),
                            Address = "Yüksek Kaldırım Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9828 41.025)"),
                            Name = "Galata Altı Kahvesi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000031"),
                            Address = "Perşembe Pazarı Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9714 41.0247)"),
                            Name = "Perşembe Pazarı Lokantası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000032"),
                            Address = "Necatibey Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9752 41.0228)"),
                            Name = "Rıhtım Fotoğraf Galerisi",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000033"),
                            Address = "Bankalar Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.981 41.0244)"),
                            Name = "Yeraltı Plak Pazarı",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000034"),
                            Address = "Kılıç Ali Paşa Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.9851 41.023)"),
                            Name = "Gün Doğumu Fırını",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000035"),
                            Address = "Voyvoda Cd., Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.98 41.0258)"),
                            Name = "Karaköy Kent Hafızası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000036"),
                            Address = "Karaköy Rıhtımı, Beyoğlu",
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.973 41.02)"),
                            Name = "Liman Seyir Terası",
                            NeighborhoodId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", "discovery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Name = "Aile Dostu",
                            Slug = "aile-dostu"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Name = "Bütçe Dostu",
                            Slug = "butce-dostu"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Name = "Manzaralı",
                            Slug = "manzarali"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Name = "Tarihi",
                            Slug = "tarihi"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Name = "Vegan Seçenekli",
                            Slug = "vegan-secenekli"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Name = "Gece Açık",
                            Slug = "gece-acik"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            Name = "Evcil Hayvan Dostu",
                            Slug = "evcil-hayvan-dostu"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            Name = "Erişilebilir",
                            Slug = "erisilebilir"
                        });
                });

            modelBuilder.Entity("PlaceTag", b =>
                {
                    b.HasOne("Rota.Modules.Discovery.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("place_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rota.Modules.Discovery.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Neighborhood", b =>
                {
                    b.HasOne("Rota.Modules.Discovery.Domain.Entities.City", "City")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Place", b =>
                {
                    b.HasOne("Rota.Modules.Discovery.Domain.Entities.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rota.Modules.Discovery.Domain.Entities.Neighborhood", "Neighborhood")
                        .WithMany("Places")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Neighborhood");
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Category", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.City", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("Rota.Modules.Discovery.Domain.Entities.Neighborhood", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
